"""update models for time management app

Revision ID: 13615e0e8154
Revises: e61893c21c09
Create Date: 2020-06-09 22:58:27.821387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13615e0e8154'
down_revision = 'e61893c21c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('People')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='User_pkey')
                    )
    op.create_table('Project',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"Project_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('start_date', sa.Date(),
                              autoincrement=False, nullable=True),
                    sa.Column('end_date', sa.Timestamp(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='Project_pkey')
                    )
    op.create_table('Workspace',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"Workspace_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('price', sa.Float(),
                              autoincrement=False, nullable=True),
                    sa.Column('start_date', sa.Date(),
                              autoincrement=False, nullable=True),
                    sa.Column('end_date', sa.Timestamp(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(('project_id', ), ['project.id'],),
                    sa.PrimaryKeyConstraint('id', name='Workspace_pkey')
                    )
    op.create_table('Workitem',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"Workitem_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('duration', sa.Float(),
                              autoincrement=False, nullable=True),
                    sa.Column('end_date', sa.Timestamp(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ('workspace_id', ), ['workspace.id'],),
                    sa.PrimaryKeyConstraint('id', name='Workitem_pkey')
                    )
    # ### end Alembic commands ###
