"""add cascade deletion

Revision ID: 270587040265
Revises: fd1b4a7caddf
Create Date: 2020-06-24 23:13:43.207976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270587040265'
down_revision = 'fd1b4a7caddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workitem', sa.Column(
        'workspace_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workitem', 'workspace', [
                          'workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('workspace', sa.Column(
        'project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workspace', 'project', [
                          'project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'project_id')
    op.drop_constraint(None, 'workitem', type_='foreignkey')
    op.drop_column('workitem', 'workspace_id')
    # ### end Alembic commands ###
