"""add user_id to Project model

Revision ID: eaac0dede227
Revises: 13615e0e8154
Create Date: 2020-06-24 22:12:56.968430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaac0dede227'
down_revision = '13615e0e8154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###
