"""test

Revision ID: fd1b4a7caddf
Revises: fc96e9e16d52
Create Date: 2020-06-24 23:12:30.262860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1b4a7caddf'
down_revision = 'fc96e9e16d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workitem_workspace_id_fkey', 'workitem', type_='foreignkey')
    op.drop_column('workitem', 'workspace_id')
    op.drop_constraint('workspace_project_id_fkey', 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('workspace_project_id_fkey', 'workspace', 'project', ['project_id'], ['id'])
    op.add_column('workitem', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('workitem_workspace_id_fkey', 'workitem', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
